name: CI Alpine Linux

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    alpine:
        # This job runs in a Docker container of the latest Alpine
        # Linux but the host is 'ubuntu-latest' since that's what
        # GitHub Actions offers that's Linux.
        runs-on: ubuntu-latest
        container: alpine:latest

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Update the image
            - name: Update the image
              run: |
                  apk update
                  apk upgrade

            # Install Build Dependencies - Part I
            - name: Install Build Dependencies - Part I
              run: apk add make git

            # This means clone the git repo
            - uses: actions/checkout@v2

            # Within the container, install the build dependencies and
            # test suite dependencies
            - name: Install Build Dependencies - Part II
              run: make instreqs

            # Set up the source tree to build
            - name: setup
              run: meson setup build --werror -Db_buildtype=debug -Db_coverage=true

            # Compile the software
            - name: build
              run: ninja -C build -v

            # Run the test suite
            - name: test
              run: meson test -C build -v

            # Generate code coverage reports (requires
            # -Db_coverage=true on 'meson setup')
            - name: coverage
              run: |
                  ninja -C build coverage
                  curl -s https://codecov.io/bash | bash
